
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-happy-cows-w24-4pm-3
owner: ucsb-cs156-w24
repo_name: proj-happy-cows-w24-4pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjY2ODkyOTQw","is_bot":false,"login":"konarkv","name":""},"headRefName":"Konark-Pagination","number":37,"title":"added tests for first and last page buttons, mutation passes locally","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-3/pull/37"},{"author":{"id":"U_kgDOBXuwTQ","is_bot":false,"login":"hugolin0","name":""},"headRefName":"Hugo-AnnouncementIssueB2","number":35,"title":"Add Controller and Tests for Announcement Issue B2","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-3/pull/35"},{"author":{"id":"MDQ6VXNlcjkxNDk5MjI5","is_bot":false,"login":"lpullela","name":""},"headRefName":"Laya-Future2","number":34,"title":"future date bug fixed","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-3/pull/34"}]
