
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-happy-cows-w24-4pm-3
owner: ucsb-cs156-w24
repo_name: proj-happy-cows-w24-4pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjkxNDk5MjI5","is_bot":false,"login":"lpullela","name":""},"headRefName":"Bonnie-and-Laya-AdminIssue2","number":25,"title":"Bonnie and laya admin issue2","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-3/pull/25"},{"author":{"id":"U_kgDOBX3XaQ","is_bot":false,"login":"bonniehuynh","name":""},"headRefName":"Bonnie-AdminIssue","number":21,"title":"bh - added showChat field and set it to true","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-3/pull/21"},{"author":{"id":"MDQ6VXNlcjQwNDAzOTY0","is_bot":false,"login":"aardvarkzone","name":"Advait Arumugam"},"headRefName":"AA-fix-leader-board","number":19,"title":"Aa fix leader board","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-3/pull/19"},{"author":{"id":"MDQ6VXNlcjY2ODkyOTQw","is_bot":false,"login":"konarkv","name":""},"headRefName":"Konark-Pagination","number":11,"title":"Konark pagination","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-3/pull/11"}]
